/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Operation;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Locale;
import java.util.TimeZone;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author Administrator
 */
public class MainScreen_Student extends javax.swing.JFrame implements ActionListener {
    String user;
    public final int ONE_SECOND = 1000; //1秒钟更新一次
    private Calendar calendar = null; //获取当前时间的日历类
    private DateFormat dateFormat = null; //时间格式类 用来格式化时间用
    private Timer timeTimer = null; //计时器
    private TimeZone currentTimeZone; //当前的时区
    
    public void actionPerformed(ActionEvent arg0) {
        this.calendar = Calendar.getInstance(this.currentTimeZone);
        Time.setText("Time：" + this.dateFormat.format(this.calendar.getTime()));

    }
    public MainScreen_Student() {
        initComponents();
        
    }

    MainScreen_Student(String id) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("MainScreen_Student");

        user=id;
        //ID.setText("ID: "+user);
         //获取时间
        this.currentTimeZone = TimeZone.getDefault();//此方法返回本地时区程序运行的地方
        this.dateFormat = DateFormat.getDateTimeInstance(2, 2, Locale.getDefault());
        this.timeTimer = new Timer(this.ONE_SECOND, this);//实例化计时器对象
        this.timeTimer.setRepeats(true);//设置重复
        this.timeTimer.start();///启动计时器
        this.timeTimer.stop();
        this.timeTimer.restart();
        try{
            Connection con=DBUtil.getConnection();
            String sql="select * from info_student where SID='"+user+"'";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnCount = rsmd.getColumnCount();
            System.out.println(columnCount);
            boolean next = rs.next();
            String[] a = new String[columnCount];  
            for(int s=0;s<columnCount;s++)
                {                                     
                     a[s]=rs.getString(s+1);                      
                }
                     SID.setText("ID: "+user);
                     Name.setText("Name: "+a[1]);
                     Gender.setText("Gender: "+a[2]);
                     Birth.setText("Birth: "+a[3]);                     
                     Major.setText("Major: "+a[4]);
                                      
        }catch(Exception e)
        {
            System.out.println(e);
        }
           
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Inquire_scr = new javax.swing.JButton();
        change_pasd = new javax.swing.JButton();
        Time = new javax.swing.JLabel();
        SID = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        Major = new javax.swing.JLabel();
        Birth = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inquire_scr.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        Inquire_scr.setText("Inquire Score");
        Inquire_scr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inquire_scrActionPerformed(evt);
            }
        });
        jPanel1.add(Inquire_scr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 140, 40));

        change_pasd.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        change_pasd.setText("Change Password");
        change_pasd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_pasdActionPerformed(evt);
            }
        });
        jPanel1.add(change_pasd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 140, 40));

        Time.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        Time.setForeground(new java.awt.Color(255, 255, 255));
        Time.setText("Time:");
        jPanel1.add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 200, -1));

        SID.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        SID.setForeground(new java.awt.Color(255, 255, 255));
        SID.setText("ID:");
        jPanel1.add(SID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 160, -1));

        Name.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Name:");
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 160, -1));

        Gender.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        Gender.setForeground(new java.awt.Color(255, 255, 255));
        Gender.setText("Gender:");
        jPanel1.add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 110, -1));

        Major.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        Major.setForeground(new java.awt.Color(255, 255, 255));
        Major.setText("Major:");
        jPanel1.add(Major, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 170, -1));

        Birth.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        Birth.setForeground(new java.awt.Color(255, 255, 255));
        Birth.setText("Birth:");
        jPanel1.add(Birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 190, 20));

        Back.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/背景图1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Inquire_scrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inquire_scrActionPerformed
        Inquirescore s = new Inquirescore(user);
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_Inquire_scrActionPerformed

    private void change_pasdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_pasdActionPerformed
        ChangePassword s = new ChangePassword(user);
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_change_pasdActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        Login s = new Login();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainScreen_Student().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Birth;
    private javax.swing.JLabel Gender;
    private javax.swing.JButton Inquire_scr;
    private javax.swing.JLabel Major;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel SID;
    private javax.swing.JLabel Time;
    private javax.swing.JButton change_pasd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
