
package Operation;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Locale;
import java.util.TimeZone;
import javax.swing.Timer;
/**
 *
 * @author Lindens
 */
public class MainScreen_Teacher extends javax.swing.JFrame implements ActionListener {
    String  user;
    public final int ONE_SECOND = 1000; //1秒钟更新一次
    private Calendar calendar = null; //获取当前时间的日历类
    private DateFormat dateFormat = null; //时间格式类 用来格式化时间用
    private Timer timeTimer = null; //计时器
    private TimeZone currentTimeZone; //当前的时区

    public void actionPerformed(ActionEvent arg0) {
        this.calendar = Calendar.getInstance(this.currentTimeZone);
        Time.setText("Time：" + this.dateFormat.format(this.calendar.getTime()));

    }
    public MainScreen_Teacher() {
        initComponents();
    }

    public MainScreen_Teacher(String id) {
        initComponents();
        setTitle("MainScreen_Teacher");
        setResizable(false);
        setLocationRelativeTo(null);
  
        user=id;
        this.currentTimeZone = TimeZone.getDefault();//此方法返回本地时区程序运行的地方
        this.dateFormat = DateFormat.getDateTimeInstance(2, 2, Locale.getDefault());
        this.timeTimer = new Timer(this.ONE_SECOND, this);//实例化计时器对象
        this.timeTimer.setRepeats(true);//设置重复
        this.timeTimer.start();///启动计时器
        this.timeTimer.stop();
        this.timeTimer.restart();
        try{
            Connection con=DBUtil.getConnection();
            String sql="select * from info_teacher where TID='"+user+"'";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnCount = rsmd.getColumnCount();
            System.out.println(columnCount);
            boolean next = rs.next();
            String[] a = new String[columnCount];  
            for(int s=0;s<columnCount;s++)
                {                                     
                     a[s]=rs.getString(s+1);
                }
                     ID.setText("ID: "+user);
                     Name.setText("Name: "+a[1]);
                     Gender.setText("Gender: "+a[3]);
                     Education.setText("Education: "+a[4]);
                     Birth.setText("Birth: "+a[5]); 
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }
    


    /**
     * Creates new form Main_Screen
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logging = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Record = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        ID = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Birth = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        Education = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        Background_Image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logging.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        Logging.setText("Logging data");
        Logging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoggingActionPerformed(evt);
            }
        });
        jPanel1.add(Logging, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 152, 35));

        Back.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 152, 35));

        Record.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        Record.setText("Record score");
        Record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecordActionPerformed(evt);
            }
        });
        jPanel1.add(Record, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 152, 35));

        Search.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        Search.setText("Search & Delete");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 152, 35));

        ID.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 255));
        ID.setText("ID:");
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        Name.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Name:");
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        Birth.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        Birth.setForeground(new java.awt.Color(255, 255, 255));
        Birth.setText("Birth:");
        jPanel1.add(Birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        Gender.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        Gender.setForeground(new java.awt.Color(255, 255, 255));
        Gender.setText("Gender:");
        jPanel1.add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        Education.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        Education.setForeground(new java.awt.Color(255, 255, 255));
        Education.setText("Education:");
        jPanel1.add(Education, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        Time.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        Time.setForeground(new java.awt.Color(255, 255, 255));
        Time.setText("Time:");
        jPanel1.add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 190, -1));

        Background_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/背景图1.png"))); // NOI18N
        jPanel1.add(Background_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        Search k = new Search(user);
        k.setVisible(true);
        dispose();
    }//GEN-LAST:event_SearchActionPerformed

    private void RecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecordActionPerformed
        Record s = new Record(user);
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_RecordActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        Login l = new Login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void LoggingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoggingActionPerformed
        Logging s = new Logging(user);
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_LoggingActionPerformed
        
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen_Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen_Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen_Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen_Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {               
                new MainScreen_Teacher().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Background_Image;
    private javax.swing.JLabel Birth;
    private javax.swing.JLabel Education;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel ID;
    private javax.swing.JButton Logging;
    private javax.swing.JLabel Name;
    private javax.swing.JButton Record;
    private javax.swing.JButton Search;
    private javax.swing.JLabel Time;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
