/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Operation;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lindens
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Logging
     */
    public Register() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        btm = new javax.swing.JRadioButton();
        btf = new javax.swing.JRadioButton();
        year = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        month = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        day = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        confirm_button = new javax.swing.JButton();
        cancel_back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        place = new javax.swing.JTextArea();
        education = new javax.swing.JComboBox();
        psdc = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        psd = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gender:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Birth:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Native place:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("ID:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 100, -1));

        buttonGroup1.add(btm);
        btm.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        btm.setForeground(new java.awt.Color(51, 51, 51));
        btm.setText("M");
        jPanel1.add(btm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        buttonGroup1.add(btf);
        btf.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        btf.setSelected(true);
        btf.setText("F");
        btf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfActionPerformed(evt);
            }
        });
        jPanel1.add(btf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004" }));
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 56, -1));

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("年");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 48, -1));

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("月");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("日");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 99, -1));

        jLabel10.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Password Confirm:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Education:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, 20));

        confirm_button.setText("Submit");
        confirm_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(confirm_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        cancel_back.setText("Back");
        cancel_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_backActionPerformed(evt);
            }
        });
        jPanel1.add(cancel_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        place.setColumns(20);
        place.setRows(5);
        jScrollPane1.setViewportView(place);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 180, 70));

        education.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bachelor", "Master", "Docter" }));
        education.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                educationActionPerformed(evt);
            }
        });
        jPanel1.add(education, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        psdc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psdcActionPerformed(evt);
            }
        });
        jPanel1.add(psdc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 170, -1));

        jLabel12.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Password:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        psd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psdActionPerformed(evt);
            }
        });
        jPanel1.add(psd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 170, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/背景图.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setNextFocusableComponent(confirm_button);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btfActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void confirm_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_buttonActionPerformed
        try {
            PreparedStatement pst1;
            PreparedStatement pst2;
            Connection con=DBUtil.getConnection();
            String sql1 = "insert into info_teacher (TID,TName,TPassword,TGender,Education,TBirth,Nativeplace) values(?,?,?,?,?,?,?)";
            pst1 = con.prepareStatement(sql1);
            String sex;
            if(psd.getText().equals(psdc.getText()))
            {            
            pst1.setString(1, id.getText());
            pst1.setString(2, name.getText());
            pst1.setString(3, psd.getText());
            if (btm.isSelected()) {
                sex = "M";
            } else {
                sex = "F";
            }
            pst1.setString(4, sex);
            String edu = (String) education.getSelectedItem();
            pst1.setString(5, edu);
            String birth = (String) year.getSelectedItem() + "/" + (String) month.getSelectedItem() + "/" + (String) day.getSelectedItem();
            pst1.setString(6, birth);
            pst1.setString(7, place.getText());
            System.out.println(pst1);
            pst1.executeUpdate();
            String sql2 = "insert into user_teacher (TID,TPassword) values(?,?)";
            pst2 = con.prepareStatement(sql2);
            pst2.setString(1, id.getText());
            pst2.setString(2, psd.getText());
            pst2.executeUpdate();
            dispose();
            pst1.close();
            pst2.close();
            con.close();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"The password doesn't match","Error",JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        Login s= new Login();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_confirm_buttonActionPerformed

    private void cancel_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_backActionPerformed
        Login s= new Login();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancel_backActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void educationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_educationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_educationActionPerformed

    private void psdcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psdcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psdcActionPerformed

    private void psdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psdActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Register().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btf;
    private javax.swing.JRadioButton btm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel_back;
    private javax.swing.JButton confirm_button;
    private javax.swing.JComboBox day;
    private javax.swing.JComboBox education;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox month;
    private javax.swing.JTextField name;
    private javax.swing.JTextArea place;
    private javax.swing.JPasswordField psd;
    private javax.swing.JPasswordField psdc;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables
}
