package Operation;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lindens
 */
public class Search extends javax.swing.JFrame {
    String get_user;
    public Search() {
        initComponents();
        
    }

    Search(String user) {
        initComponents();
        get_user=user;
        setTitle("Search");
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        SName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SID = new javax.swing.JTextField();
        ShowAll = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_stu = new javax.swing.JTable();
        Search = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, 20));
        jPanel1.add(SName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 100, -1));

        jLabel3.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student number:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));
        jPanel1.add(SID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, -1));

        ShowAll.setText("All");
        ShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAllActionPerformed(evt);
            }
        });
        jPanel1.add(ShowAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 80, -1));

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 80, -1));

        table_stu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "SID", "SName", "SGender", "SBirth", "Major", "Enrollmentyear", "Nativeplace"
            }
        ));
        jScrollPane1.setViewportView(table_stu);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 480, 280));

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 10, 90, -1));

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/背景图.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAllActionPerformed
        try {
            PreparedStatement pst;
            ResultSet rs;
            Connection con=DBUtil.getConnection();
            String sql="select * from info_student";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnCount = rsmd.getColumnCount();
            DefaultTableModel tm=(DefaultTableModel) table_stu.getModel();
            tm.setColumnCount(0);
            tm.setRowCount(0);
            for (int i = 1; i <=columnCount; i++) {
                tm.addColumn(rsmd.getColumnName(i));
            }
            while(rs.next())
            {
                Object[] a = new Object[columnCount];
                for(int s=0;s<columnCount;s++)
                {
                    a[s]=rs.getString(s+1);
                }
                tm.addRow(a);
            }
            SID.setText("");
            SName.setText("");
            tm.fireTableDataChanged();
            pst.close();
            con.close();
            rs.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_ShowAllActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        try {
            PreparedStatement pst;
            ResultSet rs;
            Connection con=DBUtil.getConnection();
            String sql="select * from info_student where SID=? and SName=?";
            pst=con.prepareStatement(sql);
            pst.setString(1,SID.getText());
            pst.setString(2,SName.getText());
            rs=pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnCount = rsmd.getColumnCount();
            DefaultTableModel tm=(DefaultTableModel) table_stu.getModel();
            tm.setColumnCount(0);
            tm.setRowCount(0);
            if(SID.getText().length()==0)
            {
                JOptionPane.showMessageDialog(null, "Empty ID","Warning",JOptionPane.WARNING_MESSAGE); 
            }
            else if(SName.getText().length()==0)
            {
                JOptionPane.showMessageDialog(null, "Empty Name","Warning",JOptionPane.WARNING_MESSAGE); 
            }
            else if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "没有此学生记录");
            }
            else {
                for (int i = 1; i <=columnCount; i++) {
                tm.addColumn(rsmd.getColumnName(i));
            }
             String[] a = new String[columnCount];
             for(int s=0;s<columnCount;s++)
                {                
                     a[s]=rs.getString(s+1);               
                }
                tm.addRow(a);
                
            //}
            SID.setText("");
            SName.setText("");
            tm.fireTableDataChanged();
            pst.close();
            con.close();
            rs.close();
            }
        }catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        MainScreen_Teacher s = new MainScreen_Teacher(get_user);
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
       try {
            PreparedStatement pst1;
            PreparedStatement pst2;
            PreparedStatement pst3;
            PreparedStatement pst4;
            ResultSet rs;
            Connection con=DBUtil.getConnection();
            String sql="delete from info_student where SID=? and SName=?";
            pst1=con.prepareStatement(sql);
            pst1.setString(1,SID.getText());
            pst1.setString(2,SName.getText());
            pst1.executeUpdate();
            sql="delete from user_student where SID=?";
            pst2=con.prepareStatement(sql);
            pst2.setString(1,SID.getText());
            pst2.executeUpdate();
            sql="delete from stu_score where SID=?";
            pst3=con.prepareStatement(sql);
            pst3.setString(1,SID.getText());
            pst3.executeUpdate();
            sql="select * from info_student";
            pst4=con.prepareStatement(sql);
            rs=pst4.executeQuery();
            rs.next();
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnCount = rsmd.getColumnCount();
            DefaultTableModel tm=(DefaultTableModel) table_stu.getModel();
            tm.setColumnCount(0);
            tm.setRowCount(0);
            for (int i = 1; i <=columnCount; i++) {
                tm.addColumn(rsmd.getColumnName(i));
            }
            while(rs.next())
            {
                Object[] a = new Object[columnCount];
                for(int s=0;s<columnCount;s++)
                {
                    a[s]=rs.getString(s+1);
                }
                tm.addRow(a);
            }
            SID.setText("");
            SName.setText("");
            tm.fireTableDataChanged();
            pst1.close();
            pst2.close();
            pst3.close();
            con.close();
            rs.close();
            
       }catch(Exception e)
       {
           System.out.println(e);
       }
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Search().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField SID;
    private javax.swing.JTextField SName;
    private javax.swing.JButton Search;
    private javax.swing.JButton ShowAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_stu;
    // End of variables declaration//GEN-END:variables
}
